version: 2.1

jobs:
  run-tests:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
        name: Install yarn
        command: |
          curl -o- -L https://yarnpkg.com/install.sh | bash
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
          # paths:
          #   - ~/.cache/yarn
      - run:
        name: Test
        command: yarn test

workflows:
  version: 2
  run-tests:
    jobs:
      - run-tests
